OneToMany/OneToMany/Models/BaseEntity.cs
namespace OneToMany.Models
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }
        public bool SoftDeleted { get; set; } = false;
        public DateTime CreatedDate { get; set; } = DateTime.Now;
    }
}

OneToMany/OneToMany/Models/Blog.cs
namespace OneToMany.Models
{
    public class Blog :BaseEntity
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}

OneToMany/OneToMany/Models/Category.cs
namespace OneToMany.Models
{
    public class Category:BaseEntity
    {
        public string Name { get; set; }
        public ICollection<Product> Product { get; set; }
    }
}

OneToMany/OneToMany/Models/Discount.cs
namespace OneToMany.Models
{
    public class Discount :BaseEntity
    {
        public string Name { get; set; }
        public byte Percent { get; set; }
        public ICollection<Product> Product { get; set; }
    }
}

OneToMany/OneToMany/Models/Expert.cs
namespace OneToMany.Models
{
    public class Expert :BaseEntity
    {
        public string Image { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
    }
}

OneToMany/OneToMany/Models/Instagram.cs
namespace OneToMany.Models
{
    public class Instagram : BaseEntity
    {
        public string Images{ get; set; }
    }
}

OneToMany/OneToMany/Models/Product.cs
namespace OneToMany.Models
{
    public class Product:BaseEntity
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public ICollection<ProductImage> ProductImage { get; set; }
        public int? DiscountId { get; set; }
        public Discount Discount { get; set; }
    }
}

OneToMany/OneToMany/Models/ProductImage.cs
namespace OneToMany.Models
{
    public class ProductImage:BaseEntity
    {
        public string Image { get; set; }
        public bool IsMain { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

OneToMany/OneToMany/Models/Slider.cs
namespace OneToMany.Models
{
    public class Slider :BaseEntity
    {
        public string Image { get; set; }
    }
}

OneToMany/OneToMany/Models/SliderInfo.cs
namespace OneToMany.Models
{
    public class SliderInfo :BaseEntity
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string SignImage { get; set; }
    }
}

OneToMany/OneToMany/ViewModels/HomeVM.cs
using OneToMany.Models;

namespace OneToMany.ViewModels
{
    public class HomeVM
    {
        public IEnumerable<Slider> Slider { get; set; }
        public SliderInfo SliderInfo { get; set; }
        public IEnumerable<Blog> Blogs { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public IEnumerable<Product> Product{ get; set; }
        public IEnumerable<Expert> Experts { get; set; }
        public IEnumerable<Instagram> Instagrams { get; set; }


    }
}

OneToMany/OneToMany/ViewModels/ProductDetailVM.cs
using OneToMany.Models;

namespace OneToMany.ViewModels
{
    public class ProductDetailVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CategoryName { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public List<ProductImage> Images { get; set; }
        public decimal DiscountPrice { get; set; }
        public byte Percent { get; set; }
    }
}

OneToMany/OneToMany/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OneToMany.Data;
using OneToMany.Models;

namespace OneToMany.Controllers
{
    public class BlogController : Controller
    {
        private readonly AppDbContext _context;
        public BlogController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? id)
        {
            if (id is null) return BadRequest();
            Blog blog = await _context.Blogs.Where(m => !m.SoftDeleted).FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null) return NotFound();
            return View(blog);
        }
    }
}

OneToMany/OneToMany/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OneToMany.Data;
using OneToMany.Models;
using OneToMany.ViewModels;
using System.Diagnostics;

namespace OneToMany.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;
        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Slider> sliders= await _context.Sliders.Where(m=>!m.SoftDeleted).ToListAsync();
            SliderInfo sliderInfo = await _context.SliderInfos.Where(m => !m.SoftDeleted).FirstOrDefaultAsync();
            IEnumerable<Blog> blogs = await _context.Blogs.Where(m=>!m.SoftDeleted).OrderByDescending(m=>m.Id).Take(3).ToListAsync();
            IEnumerable<Category> categories = await _context.Categories.Where(m => !m.SoftDeleted).ToListAsync();
            IEnumerable<Product> products = await _context.Products.Include(m=>m.ProductImage).Where(m => !m.SoftDeleted).ToListAsync();
            IEnumerable<Expert> experts = await _context.Experts.Where(m => !m.SoftDeleted).ToListAsync();
            IEnumerable<Instagram> instagrams = await _context.Instagrams.Where(m => !m.SoftDeleted).ToListAsync();

            HomeVM model = new HomeVM()
            {
                Slider = sliders,
                SliderInfo = sliderInfo,
                Blogs = blogs,
                Categories = categories,
                Product = products,
                Experts = experts,
                Instagrams = instagrams
            };

            return View(model);
        }
    }
}

OneToMany/OneToMany/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OneToMany.Data;
using OneToMany.Models;
using OneToMany.ViewModels;

namespace OneToMany.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _context;
        public ProductController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int? id)
        {
            if (id is null) return BadRequest();

            Product product = await _context.Products.Include(m=>m.Discount).Include(m => m.ProductImage).Include(m => m.Category).Where(m => !m.SoftDeleted).FirstOrDefaultAsync(m=>m.Id == id);

            if (product == null) return NotFound();

            ProductDetailVM model = new()
            {
                Id = product.Id,
                Name = product.Name,
                CategoryName = product.Category.Name,
                Description = product.Description,
                Price = product.Price,
                Images = product.ProductImage.ToList(),
                DiscountPrice = product.Price - (product.Price * product.Discount.Percent) / 100,
                Percent = product.Discount.Percent
            };
            return View(model);
        }
    }
}

OneToMany/OneToMany/Views/Blog/Index.cshtml
@model Blog
    @{
        ViewData["Title"] = "Index";
    }
    <!DOCTYPE html>
    <html>
    <head>
        <title>Product Detail Sayfası</title>
    </head>
    <style>
        .main-image {
            display: block;
            width: 370px;
            height: 500px;
            border: 1px solid #ccc;
            box-shadow: 0 0 5px #ccc;
            margin-bottom: 10px;
        }

        .product-container {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            margin: 20px;
            padding: 20px;
            background-color: #fff;
        }

        .product-gallery {
            display: flex;
            width: 100%;
            justify-content: space-around;
            flex-direction: row;
            justify-content: center;
        }

        .gallery-image {
            width: 115px;
            height: 115px;
            border: 1px solid #ccc;
            object-fit: cover;
            cursor: pointer;
        }

            .gallery-image.active {
                border-color: #008CBA;
            }

        .product-description {
            width: 70%;
            height: 600px;
        }

            .product-description h1 {
                font-size: 36px;
                font-weight: bold;
                margin-bottom: 20px;
            }

            .product-description p {
                font-size: 16px;
                line-height: 1.5;
                margin-bottom: 20px;
                text-align: justify;
                width: 600px;
            }

        .thumbnails {
            width: 370px;
            display: flex;
            justify-content: space-between;
        }

        .image-gallery {
            width: max-content;
        }

    </style>
    <body>
        <div class="product-container">
            <div class="image-gallery">
                <img class="main-image" src="~/img/@Model.Image">
            </div>
            <div class="product-description">
                <h1>@Model.Title</h1>
                <p>@Model.Description</p>
            </div>
        </div>


    </body>
    <script>
        const galleryImages = document.querySelectorAll(".gallery-image");
        const mainImage = document.querySelector(".main-image");

        // Set the main image to the first gallery image
        mainImage.src = galleryImages[0].src;

        // Add click listeners to each gallery image
        galleryImages.forEach((image) => {
            image.addEventListener("click", () => {
                // Set the main image to the clicked gallery image
                mainImage.src = image.src;

                // Remove the "active" class from all gallery images
                galleryImages.forEach((image) => {
                    image.classList.remove("active");
                });

                // Add the "active" class to the clicked gallery image
                image.classList.add("active");
            });
        });



    </script>
    </html>

OneToMany/OneToMany/Views/Home/Index.cshtml
@model HomeVM
@{
    ViewData["Title"] = "Home Page";
}

    <!-- MAIN START -->

    <main>

        <!-- SLIDER START -->

        <section id="slider">
            <div class="owl-carousel slider">
                @foreach (var slider in Model.Slider)
                {
                    <div> <img src="~/img/@slider.Image" alt=""> </div>
                }
            </div>
            <div class="container context pl-lg-5 ml-lg-3">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="text">
                            @Html.Raw(Model.SliderInfo.Title)
                            <p class="text-black-50 d-none d-sm-block">@Model.SliderInfo.Description</p>
                        </div>
                        <div class="img">
                            <img src="~/img/@Model.SliderInfo.SignImage" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SLIDER END -->

        <!-- PRODUCTS START -->

        <section id="products">
            <div class="container">
                <div class="row pt-5">
                    <div class="col-12 d-flex justify-content-between">
                        <ul class="category-mobile d-md-none list-unstyled">
                            <li>
                                <a href="" class="categories mr-2">Categories</a>
                                <i class="fas fa-caret-down"></i>
                                <ul class="category list-unstyled" style="display: none;">
                                    <li><a href="" data-id="all">All</a></li>
                                    <li><a href="" data-id="popular">Popular</a></li>
                                    <li><a href="" data-id="winter">Winter</a></li>
                                    <li><a href="" data-id="various">Various</a></li>
                                    <li><a href="" data-id="exotic">Exotic</a></li>
                                    <li><a href="" data-id="green">Greens</a></li>
                                    <li><a href="" data-id="cactuse">Cactuses</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="category d-none d-md-flex list-unstyled">
                            <li><a href="" data-id="all">All</a></li>
                            @foreach (var item in Model.Categories)
                        {
                             <li><a href="" data-id="@item.Id">@item.Name</a></li>

                        }
                        </ul>
                        <ul class="list-unstyled">
                            <li>
                                <a href="" class="mr-2">Filter</a>
                                <i class="fas fa-caret-down"></i>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    @foreach (var item in Model.Product)
                {
                                        <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
                        <div class="product-item text-center" data-id="@item.CategoryId">
                            <div  class="img">
                                <a  asp-controller="Product" asp-action="Index" asp-route-id="@item.Id">
                                    <img src="~/img/@item.ProductImage.Where(m=>m.IsMain).FirstOrDefault().Image" class="img-fluid" alt="">
                                </a>
                            </div>
                            <div class="title mt-3">
                                <h6>@item.Name</h6>
                            </div>
                            <div class="price">
                                <span class="text-black-50">Add to cart</span>
                                <span class="text-black-50">$@item.Price</span>
                            </div>
                        </div>
                    </div>
                }

                </div>
            </div>
        </section>

        <!-- PRODUCTS END -->

        <!-- ABOUT START -->

        <section id="about">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-lg-6">
                        <div class="img">
                            <img src="~/img/h3-video-img.jpg" class="img-fluid" alt="">
                            <div
                                class="player position-absolute rounded-circle d-flex align-items-center justify-content-center">
                                <i class="fas fa-play fa-lg"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about-text mt-5 mt-lg-0 px-lg-5">
                            <h1>Suprise Your <span>Valentine!</span> Let us arrange a smile.</h1>
                            <p class="py-3">Where flowers are our inspiration to create lasting memories. Whatever the
                                occasion...</p>
                            <ul class="list-unstyled">
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Hand picked just
                                    for you.</li class="mt-3">
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Unique flower
                                    arrangements</li>
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Best way to say
                                    you care.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ABOUT END -->

        <!-- EXPERTS START -->

        <section id="experts">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>Flower Experts</h1>
                            <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                                love. Let us arrange
                                a smile for you.</p>
                        </div>
                    </div>
                </div>
                <div class="row pb-5">
                    @foreach (var item in Model.Experts)
                {
                    <div class="col-md-6 col-lg-3">
                        
                        <div class="item text-center">
                            <div class="img">
                                
                                <img src="~/img/@item.Image" class="img-fluid rounded-circle" alt="">
                           
                            </div>
                            <div class="text mt-3">
                                <h6>@item.Name</h6>
                                <p class="text-black-50">@item.Detail</p>
                            </div>
                        </div>
                        
                    </div>         
                }

                </div>
            </div>
        </section>

        <!-- EXPERTS END -->

        <!-- SUBSCRIBE START -->

        <section id="subscribe">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-12">
                        <div class="content text-center py-5">
                            <h3>Join The Colorful Bunch!</h3>
                            <div class="form-group d-flex justify-content-center flex-wrap mt-5">
                                <input type="email" placeholder="Email Address" class="form-control-lg rounded-0">
                                <button class="btn btn-danger btn-lg rounded-0 px-5 mt-3 mt-sm-0">Subscribe</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SUBSCRIBE END -->

        <!-- BLOG START -->

        <section id="blog">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>From our Blog</h1>
                            <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                                love. Let us arrange
                                a smile for you.</p>
                        </div>
                    </div>
                </div>
                <div class="row pb-5">
                    @foreach (var blog in Model.Blogs)
                {
                    <div class="col-md-6 col-lg-4">
                        <div class="item">
                            <a asp-controller="Blog" asp-action="Index" asp-route-id="@blog.Id">
                            <div class="img position-relative">
                                <img src="~/img/@blog.Image" class="img-fluid" alt="">
                                <div class="date rounded bg-light position-absolute py-1 px-2">
                                    <span>@blog.CreatedDate.ToString("MM.dd.yyyy")</span>
                                </div>
                            </div>
                            </a>
                            <div class="text mt-3 text-center px-5">
                                <h5>@blog.Title</h5>
                                <p class="text-black-50">@blog.Description</p>
                            </div>
                        </div>
                    </div>
                }
                    
                </div>
            </div>
        </section>

        <!-- BLOG END -->

        <!-- SAY START -->

        <section id="say">
            <div class="container">
                <div class="row py-5 justify-content-center">
                    <div class="col-md-8 col-xl-6">
                        <div class="owl-carousel say">
                            <div>
                                <div class="item text-center">
                                    <div class="img d-flex justify-content-center">
                                        <img src="~/img/testimonial-img-1.png" alt="">
                                    </div>
                                    <div class="text text-muted pt-3 pb-5">
                                        <i>Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus
                                            lingua. </i>
                                    </div>
                                    <div class="author">
                                        <h6>Anna Barnes</h6>
                                        <p class="text-black-50">Florist</p>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div class="item text-center">
                                    <div class="img d-flex justify-content-center">
                                        <img src="~/img/testimonial-img-2.png" alt="">
                                    </div>
                                    <div class="text text-muted pt-3 pb-5">
                                        <i>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
                                            ligula eget. </i>
                                    </div>
                                    <div class="author">
                                        <h6>Jasmine White</h6>
                                        <p class="text-black-50">Florist</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SAY END -->

        <!-- INSTAGRAM START -->

        <section id="instagram">
            <div class="owl-carousel instagram">
                @foreach (var item in Model.Instagrams)
            {
                 <div><img src="~/img/@item.Images" class="img-fluid" alt=""></div>

            }
            </div>
            <div class="hastag bg-light text-muted py-2 px-3">
                #FIORELLO
            </div>
        </section>

        <!-- INSTAGRAM END -->

    </main>

    <!-- MAIN END -->

OneToMany/OneToMany/Views/Product/Index.cshtml
@model ProductDetailVM
@{
    ViewData["Title"] = "Index";
}
<style>
    body {
        background-color: gray
    }

    .card {
        border: none
    }

    .product {
        background-color: #eee
    }

    .brand {
        font-size: 13px
    }

    .act-price {
        color: red;
        font-weight: 700
    }

    .dis-price {
        text-decoration: line-through
    }

    .about {
        font-size: 14px
    }

    .color {
        margin-bottom: 10px
    }

    label.radio {
        cursor: pointer
    }

        label.radio input {
            position: absolute;
            top: 0;
            left: 0;
            visibility: hidden;
            pointer-events: none
        }

        label.radio span {
            padding: 2px 9px;
            border: 2px solid #ff0000;
            display: inline-block;
            color: #ff0000;
            border-radius: 3px;
            text-transform: uppercase
        }

        label.radio input:checked + span {
            border-color: #ff0000;
            background-color: #ff0000;
            color: #fff
        }

    .btn-danger {
        background-color: #ff0000 !important;
        border-color: #ff0000 !important
    }

        .btn-danger:hover {
            background-color: #da0606 !important;
            border-color: #da0606 !important
        }

        .btn-danger:focus {
            box-shadow: none
        }

    .cart i {
        margin-right: 10px
    }
</style>
<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        <div class="images p-3">
                            <div class="text-center p-4"> 
                                <img id="main-image" src="~/img/@Model.Images.Where(m=>m.IsMain).FirstOrDefault().Image" width="250" /> 
                                </div>
                            <div class="thumbnail text-center"> 
                                @foreach (var item in Model.Images)
                                {
                                    <img onclick="change_image(this)" src="~/img/@item.Image" width="70">
                                }
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product p-4">
                            <div class="d-flex justify-content-between align-items-center">
                                <a asp-controller="Home" asp-action="Index">
                                <div class="d-flex align-items-center"> <i class="fa fa-long-arrow-left"></i> <span class="ml-1">Back</span> </div> <i class="fa fa-shopping-cart text-muted"></i>
                                </a>
                            </div>
                            <div class="mt-4 mb-3">
                                <span class="text-uppercase text-muted brand">@Model.CategoryName</span>
                                <h5 class="text-uppercase">@Model.Name</h5>
                                <div class="price d-flex flex-row align-items-center">
                                    <span class="act-price">$@Model.DiscountPrice</span>
                                    @if (Model.Percent != 0)
                                    {
                                        <div class="ml-2"> <small class="dis-price">$@Model.Price.ToString("0.#####")</small> <span>@Model.Percent% OFF</span> </div>
                                    }
                                </div>
                            </div>
                            <p class="about">@Model.Description</p>
                            <div class="sizes mt-5">
                                <h6 class="text-uppercase">Size</h6> <label class="radio"> <input type="radio" name="size" value="S" checked> <span>S</span> </label> <label class="radio"> <input type="radio" name="size" value="M"> <span>M</span> </label> <label class="radio"> <input type="radio" name="size" value="L"> <span>L</span> </label> <label class="radio"> <input type="radio" name="size" value="XL"> <span>XL</span> </label> <label class="radio"> <input type="radio" name="size" value="XXL"> <span>XXL</span> </label>
                            </div>
                            <div class="cart mt-4 align-items-center"> <button class="btn btn-danger text-uppercase mr-2 px-4">Add to cart</button> <i class="fa fa-heart text-muted"></i> <i class="fa fa-share-alt text-muted"></i> </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function change_image(image) {

        var container = document.getElementById("main-image");

        container.src = image.src;
    }

    document.addEventListener("DOMContentLoaded", function (event) {

    });
</script>